initial announcements
ProjectSegfault/segfautils pull request #2
Opened 2022-08-03 19:38 UTC by Odyssey346

This is an initial PR for adding announcements to segfautils.

I might switch from ``gorilla/feeds`` to an actual JSON library instead.

2022-08-03 19:40 UTC, Devnol commented
how do i remove gulag exactly

2022-08-03 19:43 UTC, Odyssey346 commented
> how do i review gulag exactly

just get an idea of the code really

2022-08-03 19:44 UTC, akisblack requested changes
mostly looks good, i would like the library change though since it will allow blog post linking. i understand that it wont be easy on your side though

2022-08-03 19:44 UTC, akisblack commented on static/announcements.html
> +    <title>Segfautils form implementation example</title>
update the title

2022-08-03 19:44 UTC, Odyssey346 commented on static/announcements.html
> +    <title>Segfautils form implementation example</title>
crap

2022-08-03 19:45 UTC, Midou36O approved these changes
LGTM

2022-08-03 19:46 UTC, akisblack approved these changes

2022-08-03 19:47 UTC, Odyssey346 commented
> since it will allow blog post linking. 
I never said this would be a "thing". I meant that I'd just get more freedom to do whatever I want with the JSON, unlike ``gorilla/feeds``, which doesn't give you much to work with since it's oriented to RSS feeds (which I totally understand)

If you'd like, we can merge the PR when I switch to a JSON library.

2022-08-03 19:52 UTC, akisblack commented
merge it now, we can switch, if we ever want, later

2022-08-03 19:54 UTC, Odyssey346 commented
Hmm, @Midou36O what's your opinion? Should we hold the PR until I switch the library for handling JSON from one that's oriented towards RSS feeds to an actual JSON library, or should we merge now and change library later?

2022-08-03 20:19 UTC, Midou36O commented
i'd rather change the to an actual JSON library before merging.

2022-08-03 20:31 UTC, Odyssey346 commented
Got it. I will fix this tomorrow, most likely.

2022-08-04 18:53 UTC, Odyssey346 commented
Switched - re-requesting review

2022-08-04 18:57 UTC, akisblack approved these changes

2022-08-04 19:13 UTC, Midou36O approved these changes
LGTM²

2022-08-04 19:17 UTC, merged